# Generated by Django 2.1.10 on 2019-07-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='ccbaLcad',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='datas',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
