# Generated by Django 2.1.1 on 2019-07-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relics', '0002_bytime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bytime',
            name='code',
        ),
        migrations.AddField(
            model_name='bytime',
            name='ccbaAsno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bytime',
            name='ccbaCtcd',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='bytime',
            name='ccbaKdcd',
            field=models.IntegerField(default=0),
        ),
    ]
