# Generated by Django 2.1.1 on 2019-07-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relics', '0004_auto_20190715_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bytime',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
