# Generated by Django 2.1.1 on 2019-07-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relics', '0005_auto_20190715_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bytime',
            name='incidents',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
